[ssh]
host = "localhost"
user = "root"
port = 22
key_path = "/root/.ssh/id_rsa"
timeout = 30
keepalive_interval = 60

[limits]
max_attempts = 3
retry_window_secs = 300

[[tunnels]]
name = "test-tunnel"
direction = "forward"
local_host = "127.0.0.1"
local_port = 8080
remote_host = "127.0.0.1"
remote_port = 80
enabled = true
